server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server:
    tomcat:
        threads:
            max: 120              # ???? ~200 ?? ?????????, ????? 80?200 ? ??????????? ?? CPU/??????
            min-spare: 10         # ??????? ?????? ????? ???????
        accept-count: 100       # ??????? ????????, ???? ??? ?????? ??????
        connection-timeout: 20000
